### ISSUE TITLE
Which one is correct license?

### ISSUE THREAD

**Issue by NoUnique** [UniversalDependencies/UD_Italian-VIT#17]
Hello,

I'm confused whether using a model trained with this corpus can be used for commercial purposes.

[LICENSE file](https://github.com/UniversalDependencies/UD_Italian-VIT/blob/master/LICENSE.txt) says it has been released as  CC BY-SA 4.0 and [README](https://github.com/UniversalDependencies/UD_Italian-VIT#readme) says it has been released as CC BY-NC-SA 3.0

Which license is correct?

**Comment by msimi** [comment]
The README is correct.

— Maria

**Comment by NoUnique** [comment]
Thank you for quick response!
