### ISSUE TITLE
tokenization of % inconsistent between ISDT and VIT

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_Italian-VIT#19]
in ISDT, the standard is to tokenize numbers and % into separate words

```
# sent_id = isst_tanl-1164
15      62      62      NUM     N       NumType=Card    16      nummod  16:nummod       SpaceAfter=No
16      %       %       SYM     SYM     _       20      nsubj   20:nsubj        _
```

in VIT, the standard is to tokenize them as one token

```
# sent_id = VIT-30
24      37,5%   37,5%   NUM     N       NumType=Card    21      conj    _       _
```

I personally have no preference, but it would be nice to standardize the tokenization.  The original VIT constituency keeps them together, I believe.

**Comment by msimi** [comment]
I fixed this on dev.

**Comment by AngledLuffa** [comment]
Thanks!
